name: CI/CD Podman Python App with GHCR

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.set-sha.outputs.sha }}
      owner_lc: ${{ steps.lower_owner.outputs.owner_lc }}
    steps:
      - uses: actions/checkout@v3

      - name: Set image SHA
        id: set-sha
        run: echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Lowercase Owner
        id: lower_owner
        run: |
          echo "owner_lc=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          OWNER_LC="${{ steps.lower_owner.outputs.owner_lc }}"
          IMAGE_BASE="ghcr.io/${OWNER_LC}/python-app"

          # Сборка и пуш
          docker build --target test -t "${IMAGE_BASE}:test-${{ github.sha }}" .
          docker push "${IMAGE_BASE}:test-${{ github.sha }}"

          docker build --target runtime -t "${IMAGE_BASE}:runtime-${{ github.sha }}" .
          docker push "${IMAGE_BASE}:runtime-${{ github.sha }}"
        shell: bash

  test:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Runs tests via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            set -e
            OWNER_LC="${{ needs.build-and-push.outputs.owner_lc }}"
            IMAGE_TEST="ghcr.io/${OWNER_LC}/python-app:test-${{ github.sha }}"

            podman login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            podman run --rm --name python-app-test --network host $IMAGE_TEST python -m pytest -v tests
            podman rmi $IMAGE_TEST || true

  deploy:
    runs-on: self-hosted
    needs: [build-and-push, test]
    steps:
      - name: Deploy runtime image via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            set -e
            OWNER_LC="${{ needs.build-and-push.outputs.owner_lc }}"
            IMAGE_RUNTIME="ghcr.io/${OWNER_LC}/python-app:runtime-${{ github.sha }}"

            podman login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

            podman stop python-app || true
            podman rm -f python-app || true

            podman run --replace -d --name python-app --network host -p 8060:8060 $IMAGE_RUNTIME

            podman images --format "{{.Repository}}:{{.Tag}}" \
            | grep "ghcr.io/${OWNER_LC}/python-app:runtime-" \
            | grep -v "${{ github.sha }}" \
            | xargs -r podman rmi -f || true
            
